[package]
name = "local_election_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
libc = "0.2"
cc = "1.0"

[[bin]]
name = "main"
path = "src/main.rs"